config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "users#index"
  resources :users
  resources :friendships, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/models/user.rb
class User < ApplicationRecord

	has_many :friendships
	has_many :friends, :through => :friendships
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user

	validates :name, presence: true, uniqueness: true
	validates :website, presence: true, uniqueness: true
	after_create :create_short_url

	def create_short_url
		begin
			firebase_object = FirebaseDynamicLink.configure do |config|
	      # the adapter should be supported by Faraday
	      # more info look at https://github.com/lostisland/faraday/tree/master/test/adapters
	      # Faraday.default_adapter is the default adapter
	      config.adapter = :httpclient

	      # required
	      config.api_key = ENV['API_KEY']

	      # default 'UNGUESSABLE'
	      config.suffix_option = 'SHORT' or 'UNGUESSABLE'

	      # required
	      config.dynamic_link_domain = 'https://challenge7.page.link'

	      # default 3 seconds
	      config.timeout = 3 

	      # default 3 seconds
	      config.open_timeout = 3
	    end

	    client = ll::Client.new
	    link = self.website
	    options = {
	      # optional, to override default dynamic_link_domain default config
	      dynamic_link_domain: 'https://challenge7.page.link', 

	      # optional, timeout of each request of this instance
	      timeout: 10, 

	      # optional, open timeout of each request of this instance
	      open_timeout: 10
	    }

	    # options argument is optional
	    result = client.shorten_link(link, options)
	    self.short_website = result[:link]
	    self.save
	  rescue Exception => e
	  	Rails.logger.info("exception occur while creating short url #{e}")
	  end  
	end	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	
	def create
		current_user = User.find_by_id(params[:user_id])
	  @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
	  if @friendship.save
	    flash[:notice] = "Added friend."
	    redirect_to root_url
	  else
	    flash[:error] = "Unable to add friend."
	    redirect_to root_url
	  end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :find_user, only: [:show]
	
	def index
		@users = User.includes(:friendships, :inverse_friends).all
	end

	def new
		@user = User.new
	end	

	def create
		@user = User.create(user_params)
		if @user.save
			WebsitesWorker.perform_async(@user.id)
			flash[:alert] = 'Member created successfully'
			redirect_to @user
		else
			flash[:error] = @user.errors.full_messages.join(', ')
			render :new
		end	
	end
		
	private
	def user_params
		params.require(:user).permit(:name, :website)
	end	

	def find_user
		@user = User.includes(:friendships, :inverse_friends).find_by_id(params[:id])
		array_id = []
		array_id.push(@user.friendships.map{|friend| friend.friend_id})
		array_id.push(@user.inverse_friends.map{|friend| friend.id})
		array_id.push(params[:id])
		@users = User.where.not(id: array_id.flatten)
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def count_friend(user)
		user.friendships.length + user.inverse_friends.length
	end	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h2>list of member</h2>
<%= link_to "Add new member", new_user_path %> 
<table style="border: 1px black solid;">
	<thead>
		<th>Name</th>
		<th>Short url</th>
		<th>Number of friends</th>
	</thead>
	<tbody>
		<% if @users.present? %>
			<% @users.each do |user| %>
				<tr>
					<td><%= link_to "#{user.name}", user_path(user) %></td>
					<td><%= user.short_website %></td>
					<td><%= count_friend(user) %></td>
				</tr>
			<% end %>
		<% else %>
		<% end %>
	</tbody>	
</table>

app/views/users/new.html.erb
<%= form_with model: @user do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, required: true %><br/>
	<%= f.label :website %>
	<%= f.url_field :website, required: true %> <br />
	<%= f.submit "Create Member"	 %>
<% end %>

app/views/users/show.html.erb
<% if @user.present? %>
	
	<h2>User profile</h2>
	Name: <%= @user.name %><br />
	WebSite <%= @user.website %><br />
	Short website <%= @user.short_website.present? ? @user.short_website : "-"  %><br />
	Data <%= @user.site_data.present? ? @user.site_data : "-" %><br />

	<input type="hidden" name="current_user" id="current_user_id" value="<%= @user.id%>">
	<br />
	<br />
	<br />
	Already friend with:- <br />
	<% @user.friendships.each do |friendship| %>
		<%= friendship.friend.name %>
	<% end %>

	<% @user.inverse_friends.each do |user| %>
		<%= user.name %>
	<% end %>
	<br />
	<br />
	<br />
	Add friends<br />
	
	<% @users.each do |user| %>
		<%= user.name %>
		<%= link_to "Add Friend", '#' , id: "create-friend", data: user.id%>
	<% end %>

<% else %>
	<tr>
		<td colspan="3">No data present for particular user</td>
	</tr>
<% end %>

<script type="text/javascript">
	$('#create-friend').click(function(){
		$.ajax({
	    type: 'POST',
	    url: '<%= friendships_path %>',
	    data: { user_id: $("#current_user_id").val(), friend_id: $(this).attr("data")},
	    dataType: 'script',
	    success: function(response) {
	    }
  	});
	});
</script>